name: Deploy Hello World to ACA
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name cac1825fbddfacr

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          resourceGroup: abir_rg_5343
          containerAppName: hello-eden-app
          dockerfilePath: Dockerfile
          imageToBuild: cac1825fbddfacr.azurecr.io/hello-eden-app:${{ github.sha }}
          acrName: cac1825fbddfacr
